name: Full Sanity Test Automation
env:
  BRANCH_TO_CHECKOUT: feature/Mens-website-corrections

on:
  schedule:
    - cron: '30 03 * * *'

  workflow_dispatch:
    inputs:

jobs:
  WEB-Sanity-Build:
    runs-on:
      - self-hosted
    steps:
      - name: check
        run: java -version

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Docker Restart
        run: |
          ls
          chmod +x ./restartDocker.sh
          ./restartDocker.sh 4443 7904

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: checkout ${{env.BRANCH_TO_CHECKOUT}} branch
        run: |
          ls
          git pull
          git checkout $BRANCH_TO_CHECKOUT
          ls

      - name: WEB Women Sanity build
        if: always()
        run: |
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}
          export RUN_IN_CI=true
          export ENV=PROD
          chmod +x ./changeRpLaunchName.sh
          ./changeRpLaunchName.sh "Pernia's Women WEB Sanity Build"
          CUCUMBER_FILTER_TAGS='@web and @women and @sanity and not @WIP' mvn clean test ;

      - name: WEB Men Sanity build
        if: always()
        run: |
          export RUN_IN_CI=true
          export ENV=PROD
          chmod +x ./changeRpLaunchName.sh
          ./changeRpLaunchName.sh "Pernia's Men WEB Sanity Build"
          CUCUMBER_FILTER_TAGS='@web and @men and @sanity and not @WIP' mvn clean test ;

      - name: Stop selenium docker
        if: always()
        run: |
          ls
          chmod +x ./stopSeleniumDocker.sh
          ./stopSeleniumDocker.sh 4443

  PWA-Sanity-Build:
    runs-on: self-hosted
    steps:
      - name: check
        run: java -version

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: checkout ${{env.BRANCH_TO_CHECKOUT}} branch
        run: |
          ls
          git pull
          git checkout $BRANCH_TO_CHECKOUT
          ls

      - name: Docker Restart
        run: |
          ls
          chmod +x ./restartDocker.sh
          ./restartDocker.sh 4444 7902

      - name: PWA Sanity build
        if: always()
        run: |
          echo "RUNNING TEST IN PWA"
          export ENV=PROD
          export RUN_IN_CI=true
          chmod +x ./changeRpLaunchName.sh
          ./changeRpLaunchName.sh "Pernia's PWA Sanity Build"
          CUCUMBER_FILTER_TAGS='@pwa and @women and @sanity and not @WIP' mvn clean test

      - name: Stop selenium docker
        if: always()
        run: |
          ls
          chmod +x ./stopSeleniumDocker.sh
          ./stopSeleniumDocker.sh 4444
